CREATE TABLE voucher
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    discount_percentage     INTEGER                                 NOT NULL,
    has_usage_limit         BOOLEAN                                 NOT NULL,
    usage_limit             INTEGER DEFAULT 2147483647,
    minimum_order           INTEGER DEFAULT 0,
    maximum_discount_amount INTEGER DEFAULT 2147483647,
    CONSTRAINT pk_voucher PRIMARY KEY (id)
);